config/routes.rb
Rails.application.routes.draw do
  get 'participants/create'

  get 'participants/index'

  root 'welcome#index'

  match 'auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  match 'auth/failure', to: redirect('/'), via: [:get, :post]
  match 'signout', to: 'sessions#destroy', as: 'signout', via: [:get, :post]
  resources :users, only: :update
  resources :participants do
    member do
      get :accept
    end
  end

  resources :posts do
    resources :comments
    resources :participants

    collection do
      get :index
      get :dance
    end
  end

  resources :categories, only: [:new,:create]

  resources :categories, only: [ :index, :show ] do
    resources :posts do
      resources :comments
      resources :participants
    end

    collection do
      get :edit
    end
  end

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :posts
  attr_accessor :sub
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :user
end

app/models/participant.rb
class Participant < ActiveRecord::Base
  validates :user_id, uniqueness: {scope: :post_id}
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
  validates_presence_of :category, :user_id
  belongs_to :category
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :participants
  mount_uploader :avatar, AvatarUploader
  default_scope { order(created_at: :desc) }
  scope :ordered_by_name, -> { reorder(url: :asc) }

  before_save do
    if(self.url.include?("youtube"))
      self.url = self.url.split("=").second.split("&").first
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :posts
  has_many :comments
  has_many :participants


  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.provider = auth.provider
      user.uid      = auth.uid
      user.name     = auth.info.name
      user.image    = auth.info.image
      user.save
    end
  end


  before_update do
    if (self.ename)
    self.ename = self.ename.split.map(&:capitalize).join(' ')
      end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  private
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  include ApplicationHelper
  before_action :set_category, only: [:show]

  def index
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    @category.option = @category.option + ", sub: " +@category.sub.join(",")
    respond_to do |format|
      if @category.save
        format.html { redirect_to new_category_post_path @category}
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def show
    @posts = @category.posts
    @post = @category.posts.new
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: [@category,@posts]}
    end
  end

  def edit
    @categories = Category.all
  end

  private
  def set_category
    @category = Category.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:title,:option, sub:[])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_post
  before_action :set_comment, only: :destroy

  def create
    @comment = @post.comments.new(comment_params)
    @comment.user = current_user
    @comment.save
  end

  def destroy
    @comment.destroy
  end

  private

  def set_post
    @post = Post.find(params[:post_id])
  end

  def set_comment
    @comment = @post.comments.find(params[:id])
  end

  def comment_params
    params.require(:comment).permit(:body, :title)
  end
end

app/controllers/participants_controller.rb
class ParticipantsController < ApplicationController
  before_action :set_post
  before_action :set_participant, only: [:destroy, :accept]

  def create
    @participant = @post.participants.new
    @participant.user = current_user
    @participant.save
  end

  def accept
    @participant.update!(is_accepted:true)
  end

  def destroy
    @participant.destroy
  end

  private

  def set_post
    @post = Post.find(params[:post_id]) if params[:post_id]
  end

  def set_user
    @user = User.find(params[:id])
  end

  def set_participant
    @participant = Participant.find(params[:id])
  end

  def participant_params
    params.require(:participant)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  include ApplicationHelper
  before_action :set_category, except: [:index, :dance]
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  protect_from_forgery



  def index
  end

  def dance

  end

  def show
    respond_to do |format|
      format.html
      format.json { render json: @post}
    end
  end

  def new
    @post = @category.posts.new
  end

  def edit
  end

  def create
    @post = @category.posts.new(post_params)
    @post.user = current_user
    respond_to do |format|
      if @post.save
        format.html { redirect_to category_path(@category)}
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to [@post.category, @post], notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to category_posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  def set_category
    @category = Category.find(params[:category_id])
  end

  def set_post
    @post = @category.posts.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :date, :time, :url, :content, :avatar)
  end

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.from_omniauth(env["omniauth.auth"])
    session[:user_id] = user.id
    redirect_to root_url
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url
  end
end

app/controllers/test_controller.rb
class TestController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: :update

  def update
    @user.update(user_params)
    @ename = @user.ename



    respond_to do |format|
      format.js
    end
  end

  private

  def user_params
    params.require(:user).permit(:ename)
  end

  def set_user
    @user = User.find(params[:id])
  end

  def qualified_user_only
    current_user == @user
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def embed(youtube_url)
    if youtube_url include? "youtube"
      youtube_id = youtube_url.split("=").last
      content_tag(:iframe, nil, src: "//www.youtube.com/embed/#{youtube_id}")
    end
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
  def embed(youtube_url)
    youtube_id = youtube_url.split("=").last
    return youtube_id
  end

  def checked(area)
    @category.sub.nil? ? false : @category.sub.math(area)
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/participants_helper.rb
module ParticipantsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
  def embed(youtube_url)
    youtube_id = youtube_url.split("=").last
    return youtube_id
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/test_helper.rb
module TestHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/categories/_form.html.erb
<div class="container">
  <div class="section">
    <%= form_for(@category) do |f| %>
        <div class="row">
          <div class="input-field col">
            <%= f.text_field :title, :id => "text", :class => "text" %>
            <label class="active" for="category_title">Category Title</label>
          </div>
        </div>

        <div class="row">
          <div class="input-field col ">
            <%= f.select :option, ['Video', 'Photo', 'Software', 'Language'] %>
          </div>
        </div>

        <div class="row">
          <div class="input-field col">
            <%= f.select :sub, options_for_select(["Location", "Date", "Log", "Comment"]), {}, {:multiple => true} %>
          </div>
        </div>


        <div class="row">
          <div class="actions">
            <%= button_tag(:class => "btn-floating btn-small teal lighten-2") do %>
                <i class="material-icons">publish</i>
            <% end %>
          </div>
        </div>
    <% end %>
  </div>
</div>

<script>
  $(document).ready(function () {
    $('select').material_select();
  });
</script>

app/views/categories/edit.html.erb
<div class="container">
  <div class="section">


    <ul>
      <% @categories.each do |category| %>
          <div class="row">
            <ol>
              <h4>
                <%= link_to category.title, new_category_post_path(category), class: "wirte_post" %>
              </h4>

              <% category.posts.each do |post| %>
                  <li>
                    <%= link_to post.title, edit_category_post_path(post.category, post) %>
                  </li>
              <% end %>
            </ol>
          </div>
      <% end %>
    </ul>


  </div>
</div>

app/views/categories/index.html.erb
<div>
  <h1>
    Hello world
  </h1>
</div>

app/views/categories/new.html.erb
<%= render 'form' %>

app/views/categories/show.html.erb
<style>
  .input-fixed{
    position: fixed;
    width:400px;
    height:600px;
    background-color: white;
    padding: 20px;
    text-align: center;
    display: none;
  }
  .input-background{
    position:fixed;
    background-color: rgba(0,0,0,.5);
    left:0;
    top:0;
    width: 100%;
    height:100%;
    display:none;
  }
</style>



<div class="container">
  <div class="section">
    <h4><%= @category.title %></h4>
    <div class="row">
      <%= render @category.posts %>
    </div>
  </div>

  <!--This is FORM-->
  <div class="input-background">
  </div>
  <div class="input-fixed" style="z-index: 9999">
      <% if @category.option.include?("Photo") %>
          <%= render 'posts/form_photo' %>
      <% end %>


      <% if @category.option.include?("Video") %>
          <%= render 'posts/form_video' %>
      <% end %>

      <% if @category.option.include?("Software") %>
          <%= render 'posts/form_software' %>
      <% end %>
  </div>

</div>


<script>
  $.fn.extend({
    animateCss: function (animationName) {
      var animationEnd = 'webkitAnimationEnd mozAnimationEnd MSAnimationEnd oanimationend animationend';
      if(animationName.indexOf("Out") == -1){
        $(this).show()
        $(this).addClass('animated ' + animationName).one(animationEnd, function() {
          $(this).removeClass('animated ' + animationName);
          });
      }
      else{
        $(this).addClass('animated ' + animationName).one(animationEnd, function() {
          $(this).removeClass('animated ' + animationName);
          $(this).hide();
        });
      }
    }
  });



  $(document).ready(function(){
    //Set input fixed form as defualt
    plyr.setup();
    $(".input-fixed").css({
      left:($(window).width() - $(".input-fixed").width())/2,
      top:($(window).height()-$(".input-fixed").height())/3,
    })


    $(".form_popup_btn").click(function(){
      $(".input-background").animateCss("fadeIn")
      $(".input-fixed").animateCss("slideInUp")
    })

    $(".input-background").click(function(){
      $(".input-background").fadeOut(1000)
      $(".input-fixed").animateCss("slideOutDown")
    })



//    $(".form_popup_btn").click(function(){
//      $(".input-fixed").removeClass("slideOutDown");
//      $(".input-background").fadeIn(1000);
//      $(".input-fixed").show();
//      $(".input-fixed").addClass("animated slideInUp");
//    })
//
//    $(".input-background").click(function(){
//      $(".input-background").fadeOut(1000)
//      $(".input-fixed").removeClass("slideInUp");
//      $(".input-fixed").addClass("slideOutDown");
//    })

  })
</script>

app/views/comments/_comment.html.erb
<% if(comment.title == @suboption) %>
<li id="comment_<%=comment.id %>">
  <% if (comment.body.include?("http")) %>
      <a href="<%= comment.body %>"><%= comment.body %></a>
  <% else %>
      <%= comment.user.name %>: <%= comment.body %>
  <% end %>
</li>
<% end %>

app/views/comments/_comments.html.erb
<div class="comments">
  <div class="comment_header">
    <% if @suboption == "LIKE" %>
        <p><i class="small material-icons comments_form_btn">thumb_up</i> 이런게 좋았어요!</p>
    <% end %>
    <% if @suboption == "WISH" %>
        <p><i class="small material-icons comments_form_btn">comment</i> 이런게 있으면 좋을거 같아요!</p>

  <% end %>
  </div>
  <div class="comments_list">
    <%= render "comments/list" %>
  </div>

  <div class='comments_form' style="display: none;">
    <%= render "comments/form" %>
  </div>
</div>

app/views/comments/_form.html.erb
<% comment = @post.comments.new %>
<div id="comments_form_<%=@post.id%>">
  <%= simple_form_for([@category,@post, comment], remote: true ) do | f | %>
      <div class='form-inputs'>
        <%= f.input :body, :class=>"textarea" ,label: false, placeholder: 'Add a comment.',  input_html: { rows: 5 } %>
      </div>

      <%= f.hidden_field :title, :value => @suboption%>


      <div class='form-actions'>
        <%= f.button :submit, :class=>"comment_submit_btn" %>

      </div>
  <% end %>
</div>

app/views/comments/_list.html.erb
<ul id="comments_list_<%=@post.id%>_<%= @suboption %>">
  <% if @post.comments.size > 0 %>
      <%= render @post.comments %>
  <% else %>
  <% end %>
</ul>

app/views/comments/create.js.erb
$("#comments_form_<%=@post.id %> form")[0].reset();

app/views/comments/destroy.js.erb
$("#comment_<%=@comment.id %>").slideUp('fast');

app/views/participants/_form.html.erb
<% participant = @post.participants.new %>
<div id="comments_form_<%=@post.id%>">
  <%= simple_form_for([@post, participant], remote: true ) do | f | %>
      <div class='form-actions'>
        <%= f.button :submit, "Join !", :class=>"comment_submit_btn" %>
      </div>
  <% end %>
</div>

app/views/posts/_form.html.erb
<style>
  .materialize-textarea {
    position: relative; /* Allow z-index */
    z-index: 2; /* Allow clicking through the label */
  }

  .input-field .materialize-textarea + label {
    z-index: 1; /* Allow clicking through the label */
  }
</style>

<%= form_for([@category, @post]) do |f| %>
    <div class="row">
      <div class="input-field col">
        <%= f.text_field :title, :id => "text", :class => "text" %>
        <label class="active" for="first_name2">Title</label>
      </div>
    </div>

    <div class="row">
      <div class="input-field col">
        <%= f.text_field :date, :id => "text", :class => "text" %>
        <label class="active" for="first_name2">Url</label>
      </div>
    </div>

    <div class="row">
      <div class="input-field col">
        <%= f.text_field :url, :id => "text", :class => "text" %>
        <label class="active" for="first_name2">Url</label>
      </div>
    </div>

    <div class="row">
      <div class="row">
        <div class="input-field col s12">
          <%= f.text_area :content, :id => "textarea1", :class => "materialize-textarea" %>
          <label for="textarea1">Content</label>
        </div>
      </div>
    </div>


    <div class="row">
      <div class="file-field input-field">
        <div class="btn">
          <span>File</span>
          <%= f.file_field :avatar %>
        </div>
        <div class="file-path-wrapper">
          <input class="file-path validate" type="text">
        </div>
      </div>
    </div>


    <div class="actions">
      <%= button_tag(:class => "btn-floating btn-small blue lighten-3") do %>
          <i class="material-icons">publish</i>
      <% end %>
    </div>
<% end %>

app/views/posts/_form_language.html.erb
22<%= form_for([@category, @post]) do |f| %>
    <div class="row">
      <div class="input-field col">
        <%= f.text_field :title, :id => "text", :class => "text" %>
        <label class="active" for="first_name2">Title</label>
      </div>
    </div>

    <div class="row">
      <div class="input-field col s12">
        <%= f.select :url, ['Korean', 'Spanish', 'English', 'Chinese'] %>
      </div>
    </div>

    <div class="row">
      <div class="row">
        <div class="input-field col s12">
          <%= f.text_area :content, :id => "textarea1", :class => "materialize-textarea" %>
          <label for="textarea1">Content</label>
        </div>
      </div>
    </div>


    <div class="actions">
      <%= button_tag(:class => "btn-floating btn-small blue lighten-3") do %>
          <i class="material-icons">publish</i>
      <% end %>
    </div>
<% end %>

app/views/posts/_form_photo.html.erb
<%= form_for([@category, @post]) do |f| %>
    <div class="row">
      <div class="input-field col">
        <%= f.text_field :title, :id => "text", :class => "text" %>
        <label class="active" for="first_name2">Title</label>
      </div>
    </div>

    <div class="row">
      <div class="input-field col">
        <%= f.text_field :date, :id => "text", :class => "text" %>
        <label class="active" for="first_name2">Date</label>
      </div>
    </div>
    <div class="row">
      <div class="input-field col">
        <%= f.text_field :time, :id => "text", :class => "text" %>
        <label class="active" for="first_name2">Time</label>
      </div>
    </div>

    <div class="row">
      <div class="input-field col s12">
        <%= f.text_field :url, :id => "text", :class => "text" %>
        <label class="active" for="first_name2">Image Url</label>
      </div>
    </div>

    <div class="row">
      <div class="file-field input-field">
        <div class="btn waves-effect waves-light">
          <i class="material-icons right">attach_file</i>
          <span>File</span>
          <%= f.file_field :avatar %>
        </div>
        <div class="file-path-wrapper">
          <input class="file-path validate" type="text">
        </div>
      </div>
    </div>

    <div class="row">
      <div class="input-field col s12">
        <%= f.text_area :content, :id => "textarea1", :class => "materialize-textarea" %>
        <label for="textarea1">Content</label>
      </div>
    </div>





    <div class="actions">
      <%= button_tag(:class => "btn-floating btn-small teal") do %>
          <i class="material-icons">publish</i>
      <% end %>
    </div>
<% end %>

app/views/posts/_form_software.html.erb
<%= form_for([@category, @post]) do |f| %>
    <div class="row">
      <div class="input-field col">
        <%= f.text_field :title, :id => "text", :class => "text" %>
        <label class="active" for="first_name2">Title</label>
      </div>
    </div>

    <div class="row">
      <div class="input-field col s12">
        <%= f.text_field :url, :id => "text", :class => "text" %>
        <label class="active" for="first_name2">Image Url</label>
      </div>
    </div>

    <div class="row">
      <div class="file-field input-field">
        <div class="btn waves-effect waves-light">
          <i class="material-icons right">attach_file</i>
          <span>File</span>
          <%= f.file_field :avatar %>
        </div>
        <div class="file-path-wrapper">
          <input class="file-path validate" type="text">
        </div>
      </div>
    </div>

    <div class="row">
      <div class="input-field col s12">
        <%= f.text_area :content, :id => "textarea1", :class => "materialize-textarea" %>
        <label for="textarea1">Content</label>
      </div>
    </div>





    <div class="actions">
      <%= button_tag(:class => "btn-floating btn-small teal") do %>
          <i class="material-icons">publish</i>
      <% end %>
    </div>
<% end %>

app/views/posts/_form_video.html.erb
<%= form_for([@category, @post]) do |f| %>
    <div class="row">
      <div class="input-field col">
        <%= f.text_field :title, :id => "text", :class => "text" %>
        <label class="active" for="first_name2">Title</label>
      </div>
    </div>

    <div class="row">
      <div class="input-field col s12">
        <%= f.text_field :url, :id => "text", :class => "text" %>
        <label class="active" for="first_name2">Video Url</label>
      </div>
    </div>

    <div class="row">
      <div class="row">
        <div class="input-field col s12">
          <%= f.text_area :content, :id => "textarea1", :class => "materialize-textarea" %>
          <label for="textarea1">Content</label>
        </div>
      </div>
    </div>

    <div class="actions">
      <%= button_tag(:class => "btn-floating btn-small blue lighten-3") do %>
          <i class="material-icons">publish</i>
      <% end %>
    </div>
<% end %>

app/views/posts/_post.html.erb
<div class="col s12 m6" style="margin-bottom: 30px">
    <!--if post is video related-->
    <% if post.category.option.include?("Video") %>
        <div class="plyr materialboxed">
          <div data-video-id="<%= post.url %>" data-type="youtube"></div>
        </div>
    <% end %>
    <!--if post is image related-->
    <% if post.category.option.include?("Photo") %>
        <% if post.url.present? %>
            <img class="materialboxed" src="<%= post.url %>" width="100%">
        <% elsif post.avatar.present? %>
            <%= image_tag(post.avatar, :class => "materialboxed", style: 'width:100%') %>
        <% end %>

    <% end %>

    <% if post.category.option.include?("Software") %>
        <% if post.url.present? %>
            <img class="materialboxed" src="<%= post.url %>" width="100%">
        <% elsif post.avatar.present? %>
            <%= image_tag(post.avatar, :class => "materialboxed", style: 'width:100%') %>
        <% end %>

    <% end %>

    <!--if post is software related-->

    <!--if post is languages related-->
</div>

app/views/posts/_update_ename.html.erb
<%= form_for(current_user, remote: true) do |f| %>
    <div class="row name-box" style="width:300px; position:relative">
      <div class="input-field col s12" style="position:absolute; left:0px; top:0px">
        <%= f.text_field :ename %>
        <label class="active" for="first_name2">English Name</label>
        <div class="actions" style="position:absolute; right:0px;top:0px;">
          <%= button_tag(:class => "waves-effect waves-light btn name-submit-btn") do %>
              submit
          <% end %>
        </div>
      </div>
    </div>
<% end %>

app/views/posts/dance.html.erb
<div class="container">
  <div class="section">
    <!--   All Post   -->
    <div class="row" style="position:relative">
    <% Post.all.each do |post| %>
          <div class="col s12 m6">
            <h5><%= post.title %></h5>
            <!-- MAIN Option 별 디자인-->
            <div class="z-depth-5">
              <% if post.category.option.include?("Video") %>
                  <div class="plyr materialboxed">
                    <div data-video-id="<%= post.url %>" data-type="youtube"></div>
                  </div>
              <% elsif post.category.option.include?("Photo") %>
                  <% if post.url.present? %>
                      <img class="materialboxed" src="<%= post.url %>" width="100%">
                  <% elsif post.avatar.present? %>
                      <%= image_tag(post.avatar, :class => "materialboxed", style: 'width:100%') %>
                  <% end %>
              <% elsif post.category.option.include?("Software") %>
                  <% if post.url.present? %>
                      <img class="materialboxed" src="<%= post.url %>" width="100%">
                  <% elsif post.avatar.present? %>
                      <%= image_tag(post.avatar, :class => "materialboxed", style: 'width:100%') %>
                  <% end %>
              <% end %>
            </div>

            <!-- SUB Option 디자인 -->
          </div>
    <% end %>
    </div>
  </div>
</div>

<script>
  $(document).ready(function(){
    plyr.setup()
  })
</script>

app/views/posts/edit.html.erb
<style>
  .center {
    position: absolute;
    width: 600px;
    left: 50%;
    margin-left: -300px;
  }
</style>

<div class="center">
  <h5>Create Post "<%= @category.title %>"</h5>

  <div>
    <div>
      <% if @category.option.include?("Photo") %>
          <%= render 'form_photo' %>
      <% end %>


      <% if @category.option.include?("Video") %>
          <%= render 'form_video' %>
      <% end %>

      <% if @category.option.include?("Language") %>
          <%= render 'form_language' %>
      <% end %>
    </div>

  </div>
</div>

app/views/posts/new.html.erb
<div class="container">
  <div class="section">
    <% if @category.option.include?("Photo") %>
        <%= render 'form_photo' %>
    <% end %>


    <% if @category.option.include?("Video") %>
        <%= render 'form_video' %>
    <% end %>

    <% if @category.option.include?("Software") %>
        <%= render 'form_software' %>
    <% end %>

  </div>
</div>

app/views/posts/show.html.erb
<div class="row pd_t-15">
  <div class="col s12">
    <div>
      <% if @post.category.option.include?("Video") %>
          <div class="plyr materialboxed">
            <div data-video-id="<%= @post.url %>" data-type="youtube"></div>
          </div>
      <% elsif @post.category.option.include?("Photo") %>
          <% if @post.url.present? %>
              <img class="picture" src="<%= @post.url %>" width="100%">
          <% elsif @post.avatar.present? %>
              <%= image_tag(@post.avatar, :class => "picture", style: 'width:100%') %>
          <% end %>
      <% elsif @post.category.option.include?("Software") %>
          <% if @post.url.present? %>
              <img class="materialboxed" src="<%= @post.url %>" width="100%">
          <% elsif @post.avatar.present? %>
              <%= image_tag(@post.avatar, :class => "materialboxed", style: 'width:100%') %>
          <% end %>
      <% end %>
    </div>

    </a>
  </div>
</div>

<div class="container">
  <div class="section">

    <div class="row pd_t-15">
      <h3 class="center-align pd_b-10"><%= @post.title %></h3>

      <div class="col l4 m4 s4 center"><p><i class="medium material-icons">language</i></p>
        <p>Genre: <%= @post.category.title %></p></div>
      <div class="col l4 m4 s4 center"><p><i class="medium material-icons">today</i></p>
        <p>날짜: <%= @post.date %></p></div>
      <div class="col l4 m4 s4 center"><p><i class="medium material-icons">schedule</i></p>
        <p>시간: <%= @post.time %></p></div>
      <!-- MAIN Option 별 디자인-->
    </div>

    <div class="row pd_t-15">
      <div class="col s12">
        <div class="flow-text">
          <%= simple_format(@post.content) %>
        </div>
      </div>
    </div>







    <div class="row">
      <div class="col s12 m12 l12">
        <h5>참여자</h5>
        <ul id="participant-true">
          <% @post.participants.each do |participant| %>
              <% if participant.is_accepted? %>
                  <li><%= participant.user.ename %></li>
              <% end %>
          <% end %>
        </ul>
        <h5>대기자</h5>
        <ul id="participant-false">
          <% @post.participants.each do |participant| %>
              <% if !participant.is_accepted? %>
                  <li id = "participantid_<%= participant.id %>">
                    <% if @post.user.id != current_user.id %>
                      <p><%= participant.user.ename %></p>
                    <% else %>

                      <p>(<%= participant.user.name %>)<%= link_to participant.user.ename, accept_participant_path(participant), remote: true, data: { confirm: "Are you sure?" } %></p>
                    <% end %>
                  </li>


        <% end %>
          <% end %>
        </ul>
      </div>
    </div>


    <% if current_user %>
    <% if @post.participants.where(user_id: current_user.id)==[] %>
        <div class="row">
          <div class="col s12 m12 l12">
            <div id="participant_form"class="participant">
              <%= render "participants/form" %>
            </div>
          </div>
        </div>

    <% end %>
    <% end %>


    <div class="row">
      <!-- SUB Option 디자인 -->
      <div class="col s12 m6 l6">
        <% if @post.category.option.include?("Comment") %>
            <% @suboption = "LIKE" %>
            <div>
              <div class="comment">
                <%= render "comments/comments" %>
              </div>
            </div>
        <% end %>
      </div>

      <div class="col s12 m6 l6">
        <% if @post.category.option.include?("Log") %>
            <% @suboption = "WISH" %>
            <div>
              <div class="comment">
                <%= render "comments/comments" %>
              </div>
            </div>
        <% end %>
      </div>
    </div>

  </div>
</div>

<script>
  $(".comments_form_btn").click(function () {
    $(this).parent().parent().parent().find($(".comments_form")).show();
  })
</script>